### ISSUE TITLE
let in ghci

### ISSUE THREAD

**Issue by alogic0** [alexeyr/miet-haskell-course#1]
https://github.com/alexeyr/miet-haskell-course/blob/bf4504116ca17dea0fb108670ce5fce3c5cb4fd2/lecture1.tex#L177

В ghci 8.2.2 `let` для определения функций не нужен. 

> Since GHC 8.0.1, you can bind values and functions to names without let statement

[User's Guide](http://downloads.haskell.org/~ghc/8.2.2/docs/html/users_guide/ghci.html#introduction-to-ghci)

**Comment by alexeyr** [comment]
Спасибо! Я помнил, что типы данных теперь в GHCi определять можно, а вот это пропустил или забыл.
